### PR TITLE
Update translation-fr.bash

### PR DESCRIPTION
**Pull request by suyaseongi**
Enhance French translation of Welcome, many mistakes that seem to come from the typical word-for-word translation of online services. More enhancements to come.

### CODE REVIEW

**Comment by killajoe** [comment]
thanks for your contribution i go tag @manuel-192 to let him check and squash-merge this!

**Review by killajoe — APPROVED** [review]

**Review by killajoe — APPROVED** [review]

**Review by killajoe — APPROVED** [review]

**Comment by manuel-192** [comment]
Thanks!
Merged and releasing as soon as possible.

**Comment by suyaseongi** [comment]
Pleased to have helped and contributed to the project :D

**Comment by manuel-192** [comment]
By the way, there are some new items to translate now.
You should see which items simply by running `eos-welcome` and looking at the log file.

**Comment by suyaseongi** [comment]
Thanks for the info, I'm gonna start working on it now !
I've just got a question about the new elements : as I first misread "nb_nofify" as "nb_notify", what does "nofify" stand for ?

**Comment by killajoe** [comment]
> By the way, there are some new items to translate now.

for german too? i can check

**Comment by suyaseongi** [comment]
> is this in addition or replacing this one?

Oh, everything I did there is continuous, so it's in addition to the previous PRs (including this one, #330). Sorry if it was unclear. I saw that the french file lacked the typo fix so I did that in a new PR, #332, but that was after I first added the 'nb_nofify' elements in #331. Hope this clears things up a bit, but if it doesn't, feel free to ask !

**Comment by killajoe** [comment]
I was only confused to see a new pr ;)=  in case it can get an issue if one tries to commit the second one before the first...

**Comment by suyaseongi** [comment]
Alright ! I'm gonna keep this in mind for future contributions :+1:

**Pull request merged**
