### PR TITLE
update version for eos-qogir-icons

### PR DESCRIPTION
**Pull request by flyingcakes85**
#347

### CODE REVIEW

**Comment by killajoe** [comment]
would need to update the package version too.. 
and lets add the relase tag too:
https://github.com/vinceliuice/Qogir-icon-theme/releases/tag/2023-06-05

**Review by killajoe — CHANGES_REQUESTED** [review]
pkgver needs to be 6

**Comment by flyingcakes85** [comment]
Hi @killajoe 

> pkgver needs to be 6

updated

> and lets add the relase tag too:
https://github.com/vinceliuice/Qogir-icon-theme/releases/tag/2023-06-05

Where exactly? Its fetching sources from `https://github.com/vinceliuice/Qogir-icon-theme/archive/refs/tags/${_srcver}.tar.gz`

**Comment by manuel-192** [comment]
Thanks for the heads up! I added the change to the official PKGBUILD and released it already as version 6-1.
Are there more changes needed or is this OK now?

**Comment by flyingcakes85** [comment]
@manuel-192  looks fine now :+1:

**Pull request closed without merging**
