### PR TITLE
Added grub-theme-endeavouros-classic and endeavouros-backgrounds-classic

### PR DESCRIPTION
**Pull request by LeSnake04**
# PKGBUILDs for the old grub themes and backgrounds

## grub-theme-endeavouros-classic
Replaces grub-theme-endeavouros with the old theme

## endeavouros-backgrounds-classic
adds old backgrounds to  `/usr/share/endeavouros/backgrounds/`
I added a `-classic` to the backgrounds to avoid conflicts with endeavouros-theming

### CODE REVIEW

**Comment by killajoe** [comment]
will not be merged till confirmation of all devs

**Comment by LeSnake04** [comment]
Me and @killajoe decided I would be the maintainers of the linked repos to avoid giving the devs to much tasks

**Comment by killajoe** [comment]
We are sorry to say that we are not able to merge this PR, we could include old themes if they would be separated packages only.

**Review by killajoe — COMMENTED** [review]
this is its own package already... so we can add it

**Comment by LeSnake04** [comment]
> 
> 
> this is its own package already... so we can add it

Made a second pull request

**Comment by killajoe** [comment]
needs a new PR for the grub-theme package to add, we will not merge changes to the default theming package.

**Pull request closed without merging**
