### PR TITLE
Added translation to Croatian language and cleaned up Serbian language

### PR DESCRIPTION
**Pull request by OutOfPhase87**
Croatian language added
Serbian language cleaned up and fixed spelling mistakes, also changed filename and language code from "sr" to "rs"
Added missing "" to both Serbian and Croatian translation

### CODE REVIEW

**Comment by manuel-192** [comment]
We now have conflicts with your modified file and our git version which I updated yesterday.
For the record, if you make modifications to your local version, it is very important to do `git pull` before making any modifications. That's how we can easily avoid similar file conflicts.

**Comment by OutOfPhase87** [comment]
Manuel, I apologize for not doing this the proper way.
Can you please confirm if all is ok now?

Many thanks for your patience.

**Comment by manuel-192** [comment]
Thanks!
There was still a typo in the HR file (_tr_lang was rs), but I fixed it. Now the new package has been released and arrives at mirrors soon.

**Comment by OutOfPhase87** [comment]
Thank you very much Manuel.

**Pull request merged**
