### PR TITLE
Update translation-pt.bash

### PR DESCRIPTION
**Pull request by hugok79**
Portuguese(pt) welcome translation completed

### CODE REVIEW

**Comment by manuel-192** [comment]
Hi!
Thanks for updating the translation.
However, your pull request is updating several other files as well. Looks like you are updating to the testing branch. But better to update the master branch, then only your modification stands out, otherwise it is confusing unfortunately.

**Comment by manuel-192** [comment]
I'll merge your new translation file manually. Could you please check that it is OK after merge.

**Comment by manuel-192** [comment]
Merged, closing.

**Comment by hugok79** [comment]
Ok, Thanks and sorry about tha. Next time I'Il pull to the master branch.
The translation is ok

**Pull request closed without merging**
