### PR TITLE
Add logout purple

### PR DESCRIPTION
**Pull request by flyingcakes85**

### CODE REVIEW

**Review by killajoe — CHANGES_REQUESTED** [review]
is name changes it can not be used when chosen automatically.. it should be replace the original one to be used per default

**Comment by flyingcakes85** [comment]
There are two in original one

xfsm-logout.svg
gnome-logout.svg

Both look identical, but have different names. Should we replace both?

**Comment by killajoe** [comment]
i would say both are symlinks to system-log-out.svg ?
/usr/share/icons/Qogir/scalable/apps/system-log-out.svg

**Comment by flyingcakes85** [comment]
> i would say both are symlinks to system-log-out.svg ? /usr/share/icons/Qogir/scalable/apps/system-log-out.svg

Ah, I didn't notice. I updated PKGBUILD to replace system-log-out itself.

**Pull request merged**
