### PR TITLE
improve PKGBUILDs formatting

### PR DESCRIPTION
**Pull request by sravanpannala**
Improve formatting of PKGBUILDs so that they can be built in a automated format.

### CODE REVIEW

**Review by flyingcakes85 — APPROVED** [review]

**Comment by killajoe** [comment]
i would think we should review all PKGBUILDS before documenting how we want them formatted ?

**Comment by sravanpannala** [comment]
Sure, makes sense. After deciding on what to do, should we have all of them in a single PR?

**Comment by killajoe** [comment]
would be the cleanest way to call out a PKGBUILD fix day where we do this all together in one call

**Review by killajoe — CHANGES_REQUESTED** [review]
to avoid from pushing package update on  mirror I set PKGBUILD to not_ready_PKGBUILD

**Pull request merged**
