### PR TITLE
Adding Vietnam's new 42tm mirror to mirrorlist

### PR DESCRIPTION
**Pull request by HoangTheBoss**

### CODE REVIEW

**Comment by HoangTheBoss** [comment]
I sent Alpix an email too.

**Comment by AlpixTM** [comment]
> @AlpixTM ? // we still missing some sort of readme ;)

Yeah.




> I sent Alpix an email too.

I will reply, it's on my to-do list, sorry.

**Comment by killajoe** [comment]
@AlpixTM no problem we have to sort out a lot of stuff .. it never ends.. ;)

**Comment by manuel-192** [comment]
Merged already.

**Pull request closed without merging**
