### PR TITLE
Update eos-install-mode-run-calamares

### PR DESCRIPTION
**Pull request by killajoe**
option -d is now    "the developer mode flash"   as Adrian says so removed  pkexec calamares -style kvantum -c /etc/calamares/ -d >> $log &

and adding -D6 is the way to go ..

Not 100% sure about the change so check this please @manuel-192 @dalto8 @Portergos

### CODE REVIEW

**Comment by killajoe** [comment]
pkexec calamares -style kvantum -D8 >> $logfile

would be better?

**Comment by dalto8** [comment]
> option -d is now "the developer mode flash"

I think he meant "flag"

> would be better?

I am not sure if there is a difference between `-D6` and `-D8` in practice.  I have used both and never noticed anything.

**Comment by killajoe** [comment]
> I think he meant "flag"

sure but it sounds nicer ;)

**Review by killajoe — COMMENTED** [review]
pkexec calamares -style kvantum -D8 >>

**Comment by killajoe** [comment]
iam still not sur eif the -c /etc/calamares part was something needed in the context of using the command inside welcome/yad ? @manuel-192

**Comment by killajoe** [comment]
but seems to work ?

**Comment by killajoe** [comment]
@manuel-192 and the addition you had added to show install mode in the start of the log?

**Pull request merged**
