### PR TITLE
Update translation-se.bash

### PR DESCRIPTION
**Pull request by bittin**
Hey!

Updated Swedish Translation not sure if all syntax is correct, as its my first time committing here so please check

### CODE REVIEW

**Comment by bittin** [comment]
@manuel-192 Updated the translation file now, can you do another check

**Comment by bittin** [comment]
100% done and working Swedish translation

**Comment by manuel-192** [comment]
Thanks! Merged and releasing soon.

**Comment by bittin** [comment]
got it now thanks :)

**Pull request merged**
