### PR TITLE
Fixed /etc/os-release (#159)

### PR DESCRIPTION
**Pull request by TruncatedDinosour**
Regarding #159

### CODE REVIEW

**Review by TruncatedDinosour — COMMENTED** [review]
Everything looks fine, every single-quote was replaced with an escaped double quote because un-escaped double quotes
would break the expression

**Comment by manuel-192** [comment]
Can you tell me exactly where the single quotes cause a problem, preferably with an example?

**Comment by killajoe** [comment]
https://github.com/endeavouros-team/PKGBUILDS/issues/159

**Comment by TruncatedDinosour** [comment]
> Can you tell me exactly where the single quotes cause a problem, preferably with an example?

#159

**Comment by manuel-192** [comment]
As this is a bug in other programs, I'll simply remove single quotes from some variable values.

**Pull request closed without merging**
