### PR TITLE
Update translation-ru.bash

### PR DESCRIPTION
**Pull request by VladimirPomogaev**
translation correction

### CODE REVIEW

**Comment by manuel-192** [comment]
Line 336 conflicts with PR #232.

**Comment by ViktorOn** [comment]
Vladimir, as I understand it, the last two strings (335, 335) that you translated are a continuation of each other in the original. I suggest you close your request.

**Comment by VladimirPomogaev** [comment]
> Владимир, как я понимаю, последние две строки (335, 335), которые вы перевели, являются продолжением друг друга в оригинале. Я предлагаю вам закрыть свой запрос.

Нет. В заново предложенном варианте убрал "лишнее" слово, на прикреплённых файлах видно
new
old

**Comment by VladimirPomogaev** [comment]
> Line 336 conflicts with PR #232.

There is no conflict. The translation in meaning remained the same, but from the point of view of the spelling of the Russian language, it became more correct in writing and reading. In the "new" version, the word "кнопка" is excluded

**Comment by manuel-192** [comment]
So... I'm merging this one. If more changes are needed, please let me know.
And please note, as I don't speak Russian, I let you both decide about the translation.

Thanks to both of you!

**Comment by ViktorOn** [comment]
> Нет. В заново предложенном варианте убрал "лишнее" слово, на прикреплённых файлах видно
Yes, you are right, then I will make a new PR

**Pull request merged**
