### PR TITLE
Update endeavouros-mirrorlist

### PR DESCRIPTION
**Pull request by The-Repo-Club**
Added my mirror and fixed the url for the github mirror

### CODE REVIEW

**Comment by AlpixTM** [comment]
Hello @The-Repo-Club,

thanks for the nice looking page.
I/We don't understand fully the way it's working and if it qualifies to be included into the mirror list.

Can you please send me a mail, so we can get the information needed to consider this request?

image

**Comment by The-Repo-Club** [comment]
This page runs off of GitHub pages and if you click one of the packages it will show the link to the file and you may understand it a bit more if you need any more info feel free to ask here

**Comment by AlpixTM** [comment]
Can you please send me a mail?

**Comment by The-Repo-Club** [comment]
Ok I sent u a email

**Pull request closed without merging**
