### PR TITLE
Add Thai translation for welcome app.

### PR DESCRIPTION
**Pull request by pannxe**
I created Thai translation for the welcome app.

Some of them are surprisingly hard to translate directly so I tweaked them a little bit, should not affect the meaning.
I think my translation is rather verbose (or is it the language nature, I am not so sure). If you think some of them are too long, feel free to comment so I can come up with the new one.

### CODE REVIEW

**Comment by manuel-192** [comment]
Thanks! Merging soon.

**Comment by manuel-192** [comment]
There's a small issue: text on buttons in the Welcome app are not left aligned, like they are in other translations. Probably is a language feature?
I can live with that, but what do you think?
It may be hard to fix though.

**Comment by pannxe** [comment]
Thai is left-align so I think it's a bug. If it's just an aesthetic issue, I think it can be fixed later.

**Comment by snehitsah** [comment]
I'm working with Hindi translations and I noticed the same thing. English text is left aligned, but Hindi text is showing centered. I tried with Japanese text, which shows up left aligned as expected. So all Asian languages are not facing the problem, but some are.

Anyways, I think this is a minor issue, and can be left as it is.

**Comment by pannxe** [comment]
Ah, so that's support my theory that because some Devanagari (and Thai) character can go on top and under the one in front of it whilst Japanese cannot.

This information may help for further investigation.

**Pull request merged**
